version: "3.3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - reverse_proxy_nw
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.abhishek0010.xyz`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-secure.service=portainer-secure"
      - "traefik.docker.network=reverse_proxy_nw"
volumes:
  portainer_data:
    name: portainer_data
networks:
  reverse_proxy_nw:
    external: true
