version: "3.3"

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - traefik_ssl_certs:/ssl_certs
    networks:
       - reverse_proxy_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # wildcard certs
      - "traefik.http.routers.wildcard-certs.tls.certresolver=godaddy"
      - "traefik.http.routers.wildcard-certs.tls.domains[0].main=abhishek0010.xyz"
      - "traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.abhishek0010.xyz"
 
      # for dashboard
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.abhishek0010.xyz`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.docker.network=reverse_proxy_nw"
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - reverse_proxy_nw
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.abhishek0010.xyz`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-secure.service=portainer-secure"
      - "traefik.docker.network=reverse_proxy_nw"
volumes:
  portainer_data:
    name: portainer_data
  traefik_ssl_certs:
    name: traefik_ssl_certs
networks:
  reverse_proxy_nw:
    external: true


