ping: {}
api:
  dashboard: true
  debug: true
log:
  level: DEBUG
  format: json
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    network: traefik-public
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
    #file:
    #filename: /dynamic.yml
certificatesResolvers:
  godaddy:
    acme:
      #caServer: https://acme-v02.api.letsencrypt.org/directory
      email: <YOUR EMAIL>
      storage: /le/acme.json
      dnsChallenge:
        provider: <YOUR DNS PROVIDER>
        resolvers:
          - "ns65.domaincontrol.com:53"
          - "ns66.domaincontrol.com:53"
