version: "3.3"

services:
  traefik:
    image: "traefik:2.10"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-public
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Make sure the volume folder is created
      - "/mnt/data/traefik/static.yml:/traefik.yml:ro"
      #- "/mnt/data/traefik/dynamic.yml:/dynamic.yml:ro"
      - "/mnt/data/traefik/acme.json:/le/acme.json"
      - "./logs/traefik:/var/log/traefik"
    deploy:
      placement:
        constraints: [node.labels.label == manager]
      labels:
        - "traefik.enable=true"
        #- "traefik.http.routers.traefik.entrypoints=http"
        #- "traefik.http.routers.traefik.rule=Host(`traefik.abhishek0010.in`)"
        #- "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
        #- "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
        #- "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
        - "traefik.http.routers.traefik-secure.rule=Host(`traefik.abhishek0010.in`)"
        #- "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik-secure.service=api@internal"
        - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080"
        #- "traefik.http.services.traefik.loadbalancer.server.scheme=https"
        - "traefik.http.routers.traefik-secure.tls=true"
        #- "traefik.http.routers.traefik-secure.entrypoints=https"
        - "traefik.http.routers.traefik-secure.tls.certresolver=godaddy"
        - "traefik.http.routers.traefik-secure.tls.domains[0].main=abhishek0010.in"
        - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.abhishek0010.in"
        - "traefik.http.routers.traefik-secure.middlewares=authelia@docker"

  my-app:
    image: containous/whoami:v1.3.0
    networks:
      - traefik-public
      command:
      - --port=8082 # Our service listens on 8082
    deploy:
      labels:
        - "traefik.enable=true"
        #- "traefik.http.routers.my-app.entrypoints=http"
        #- "traefik.http.routers.my-app.rule=Host(`whoami.abhishek0010.in`)"
        #- "treafik.http.middlewares.my-app-https-redirect.redirectscheme.scheme=https"
        #- "traefik.http.routers.my-app.middlewares=my-app-https-redirect"
        - "traefik.http.services.my-app-secure.loadbalancer.server.port=8082"
        - "traefik.http.routers.my-app-secure.middlewares=authelia@docker"
        - "traefik.http.routers.my-app-secure.rule=Host(`whoami.abhishek0010.in`)"
        #- "traefik.http.routers.my-app-secure.entrypoints=https"
        - "traefik.http.routers.my-app-secure.tls=true"
        #- "traefik.http.routers.my-app-secure.service=my-app"
        #- "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
