version: "3" # https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

services:
  cyberchef:
    image: mpepping/cyberchef:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=Host(`cyberchef.domain.in`)"
      - "traefik.http.routers.cyberchef.tls=true"
      - "traefik.http.routers.cyberchef.middlewares=authelia@docker"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=8000"
    networks:
      - reverse_proxy_nw

networks:
  reverse_proxy_nw:
    external: true
