---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  abhishek0010:
    disabled: false
    displayname: "Abhishek Kumar"
    password: <GENERATE_HASH> 
    email: abhishekism0010@gmail.com
    groups:
      - admins
      - user
      - dev
...