version: "2.3"

services:
  worker:
    container_name: container-name
    image: myoung34/github-runner:latest
    restart: always
    environment:
      REPO_URL: https://github.com/user/repo-example
      RUNNER_NAME: repo-example
      RUNNER_TOKEN: <GET FROM INSIDE THE REPO SETTINGS->RUNNERS->SELF HOSTED->NEW RUNNER>
      RUNNER_WORKDIR: /tmp/runner/work
      ORG_RUNNER: "false"
      LABELS: linux,x64,gpu
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/runner:/tmp/runner"
