api:
  dashboard: true
log:
  level: DEBUG
accessLog: {}
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  godaddy:
    acme:
      email: abhishekism0010@gmail.com
      storage: /ssl_certs/acme.json
      dnsChallenge:
        provider: godaddy
        resolvers:
          - "ns05.domaincontrol.com:53"
          - "ns06.domaincontrol.com:53"


