ping: {}
api:
  dashboard: true
  debug: true
log:
  level: DEBUG
  format: json
accessLog:
  filePath: "/var/log/accesss.log"
  format: json
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    network: reverse_proxy_nw # create a docker bridge network by this name
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  #file:
  #filename: /config.yml
certificatesResolvers:
  godaddy:
    acme:
      email: abhishekism0010@gmail.com
      storage: /le/acme.json
      dnsChallenge:
        provider: godaddy
        resolvers:
          - "ns65.domaincontrol.com:53"
          - "ns66.domaincontrol.com:53"
